name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia '16' por la versión requerida
      - name: Instalar dependencias en backend
        run: npm install
        working-directory: ./backend
      - name: Ejecutar Tests en backend
        run: npm test
        working-directory: ./backend
