name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: npm test
